### ISSUE TITLE
New features...

### ISSUE THREAD

**Issue by goofoo** [tunabrain/tungsten#39]
Hi Tunabrain.
How about add some new features, like "Path Traced Subsurface Scattering using Anisotropic Phase Functions and Non-Exponential Free Flights", "Spectral and Decomposition Tracking for Rendering Heterogeneous Volumes" and "A Practical Extension to Microfacet Theory for the Modeling of Varying Iridescence".
Thanks.

**Comment by tunabrain** [comment]
Hi,

While I would love to implement nearly all recent graphics papers, this would amount to a large chunk of work and I find myself too short on time to do that. I focus more on things relevant to my core research area, since those will directly help my work and I can justify the time spent on writing that code. However, I appreciate your suggestions.

Thanks!
Benedikt
